/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_learnjni_MyTest */

#ifndef _Included_com_example_learnjni_MyTest
#define _Included_com_example_learnjni_MyTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_learnjni_MyTest
 * Method:    WifiButton
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_learnjni_MyTest_WifiButton
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
