/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_learnjni_ControlSwitch */

#ifndef _Included_com_example_learnjni_ControlSwitch
#define _Included_com_example_learnjni_ControlSwitch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_learnjni_ControlSwitch
 * Method:    getSwitchStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_learnjni_ControlSwitch_getSwitchStatus
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
